require("user.impatient")
require("user.options")
require("user.plugins")
require("user.colorscheme")
require("user.keymaps")
require("user.telescope")
require("user.autopairs")
require("user.cmp")
require("user.lsp")
require("user.treesitter")
require("user.lualine")
-- require("user.session-lens")
require("user.rust-tools")
require("user.bufferline")
require("user.project")
require("user.leap")
require("user.toggleterm")
