local o = vim.opt
o.fileencoding = "uft-8"
o.hidden = true
o.cmdheight = 1
-- o.textwidth = 120
o.updatetime = 300
o.hlsearch = false
o.scrolloff = 8
o.number = true
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.cursorline = true
o.incsearch = true
o.undofile = true
o.undolevels = 10000
o.relativenumber = true
o.smartindent = true
o.tabstop = 2
o.softtabstop = 2
o.shiftwidth = 2
o.expandtab = true
o.colorcolumn = "120"
o.signcolumn = "yes"
vim.opt.termguicolors = true
